trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - /Data/PartnerDataPlatform/PartnerDataPlatformScopes

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
stages:
  - stage: stage
    displayName: 'Execute Stage'
    jobs:
      - job: job
        displayName: Job
        steps:
        - checkout: self
          fetchDepth: 1
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 6.x
            performMultiLevelLookup: true
            includePreviewVersions: true # Required for preview versions

        - task: DotNetCoreCLI@2
          displayName: restore
          inputs:
            command: restore
            projects: $(Build.Repository.LocalPath)/Data/ContentInsightPipeline/UtilityLib/UtilityLib/UtilityLib.csproj
            selectOrConfig: config
            feedRestore: one
            nugetConfigPath: NuGet.config

        - task: DotNetCoreCLI@2
          displayName: Build project
          inputs:
            projects: '**/UtilityLib.csproj'
            arguments: --output publish_output --configuration Release
        - task: AzureArtifacts.manifest-generator-task.manifest-generator-task.ManifestGeneratorTask@0
          displayName: 'Manifest Generator'
          inputs:
            BuildDropPath: publish_output/

        - task: ArchiveFiles@2
          displayName: Archive files
          inputs:
            rootFolderOrFile: publish_output/
            includeRootFolder: false