trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
stages:
  - stage：stage
    displayName: 'Execute Stage'
    jobs:
      - job: job
        displayName: Job
        steps:
        - task: UseDotNet@2
          displayName: 'Install .NET Core SDK'
          inputs:
            version: 6.x
            performMultiLevelLookup: true
            includePreviewVersions: true # Required for preview versions

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            feedsToUse: 'select'
            vstsFeed: 'my-vsts-feed' # A series of numbers and letters

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            arguments: '--configuration $(buildConfiguration)'
          displayName: 'dotnet build $(buildConfiguration)'